version: '3'

services:
  dbpostgresql:
    image: "postgres"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ssdba
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
  app:
    build: .
    image: appbootrest1
    container_name: appbootrest1
    ports:
      - "3001:8080"
    depends_on:
      - dbpostgresql

